services:

  postgres:
    image: postgres:17

    container_name: bodeko-postgres

    restart: unless-stopped

    env_file:
      - .env.dev

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: