spring.application.name=bodeko

spring.config.import=optional:file:.env.dev[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

app.frontend-url=${FRONTEND_URL}

spring.flyway.enabled=true

